- project:
    templates:
      - openstack-python3-charm-yoga-jobs
      - openstack-cover-jobs
#      - microk8s-func-test
    check:
      jobs:
        - charmbuild:
            nodeset: ubuntu-focal
        - zaza-smoke-test:
            nodeset: ubuntu-focal
            voting: false
    vars:
      charm_build_name: placement-k8s
      juju_channel: 3.1/stable
      juju_classic_mode: false
      microk8s_channel: 1.26-strict/stable
      microk8s_classic_mode: false
